<a href="https://colab.research.google.com/github/lupuentes33/DATA_23/blob/main/Data_Strcutures.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A DS is an object that let us store moer than one value.

Formally, a DS is **sequence** of values which can be located with an index.

# **2. Linear Algebra**


## 2.1. What is Numpy?

Numpy (Numerical Python) is a collection of functions and methods.

In [1]:
# Install the library

import numpy as np

## 2.2. Numpy arrays - vectors and matrices

*Example 1 - Column vector*

In [ ]:
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


*Example 2 - Row vector*

In [ ]:
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


*Example 3 - Matrix*

In [ ]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# nice trick

nr, nc = M.shape

# 2.3. Sciling

To access one or sveral elements of the object.

In [ ]:
# Extract the first element

## Column vector
print(a[0,0])

## Row vector
print(b[0,0])

## Matrix
print(M[0,0])

1
4
1


In [ ]:
# Extract the last element

## Column vector
print(a[-1,0])

## Row vector
print(b[0,-1])

## Matrix
print(M[-1,-1])

3
6
9


In [ ]:
# Extract a subset

## Column vector
print(a[0:2])

## Row vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[1]
 [2]]
[4 5]
[[1 2]
 [4 5]]


# 2.4. Methods

In [ ]:
# ZEROS
z1 = np.zeros(4)
print(z1)

z2 = np.zeros((3,2))
print(z2)



[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# ONES

o1 = np.ones(4)
print(o1)

o2 = np.ones((3,2))
print(o2)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[5., 5.],
       [5., 5.],
       [5., 5.]])

**ANOTHER CREATION OPTIONS**

In [ ]:
# Full

f = np.full((3,2),3.18161415)
print(f)

[[3.18161415 3.18161415]
 [3.18161415 3.18161415]
 [3.18161415 3.18161415]]


In [ ]:
# Linear sequence

np.arange(6)
np.arange(23,33)
np.arange(23,33,0.5)

array([23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. ,
       28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5])

In [ ]:
# Linear space

np.linspace(15,90,6)

array([15., 30., 45., 60., 75., 90.])

## 2.5. Random Numbers

### Uniform distribution [0,1)

In [ ]:
# A Single Value - between 0 y 1
np.random.rand()

0.2725926052826416

In [ ]:
 # Example - toss a coin

 if np.random.rand() < 0.5:
   print('head')
 else:
   print('tails')

tails


In [ ]:
# Two heads in a row

if np.random.rand() < 0.25:
   print('You win!')
else:
   print('You lose!')

You lose!


In [ ]:
# Two heads in a row

ft = np.random.rand()
if ft < 0.5:
   print('The first toss was Head')
else:
   print('The first toss was Tails')

st = np.random.rand()
if st < 0.5:
   print('The second toss was Head')
else:
   print('The second toss was Tails')

if ft < 0.5 and st < 0.5:
  print('You win!')
else:
  print('You lose!')

The first toss was Head
The second toss was Head
You win!


In [ ]:
# One dimensional array
np.random.rand(5)

array([0.50164703, 0.65864823, 0.68876111, 0.70565639, 0.53951296])

In [ ]:
# Matrix
np.random.rand(6,2)

array([[0.63991321, 0.50152781],
       [0.57744132, 0.1212596 ],
       [0.17892605, 0.39753542],
       [0.31472796, 0.56818568],
       [0.3340331 , 0.05646863],
       [0.47138729, 0.32328502]])

### Uniform distribution [a,b)

In [ ]:
# Single value
np.random.uniform(low = -10, high = 0)

-4.7845026313358785

In [ ]:
# One dimensional array
np.random.uniform(low = -10, high = 0, size = 7)

array([-3.52271041, -1.91393172, -7.26922773, -0.30452204, -6.5094994 ,
       -3.62254441, -7.2141623 ])

In [ ]:
# Matrix
np.random.uniform(low = -10, high = 0, size = (5,1))

array([[-6.7427059 ],
       [-0.68250252],
       [-7.48301665],
       [-3.47268877],
       [-7.54955926]])

** Exercise**

Simulate the sale of a shop according to

| Scenario | Prob | Sales |
|----------|------|-------|
| Bad      | 25%  | 60    |
| Normal   | 50%  | 80    |
| Wow      | 25%  | 100   |

For 5 days.

In [ ]:
# A Solution

for i in range(1,6):
  tmp = np.random.rand()
  if tmp <0.25:
    print('Day:',i,'Scenario: Bad','Units sold: 60')
  elif tmp>0.75:
    print('Day:',i,'Scenario: Wow','Units sold: 100')
  else:
    print('Day:',i,'Scenario: Normal','Units sold: 80')


Day: 1 Scenario: Normal Units sold: 80
Day: 2 Scenario: Normal Units sold: 80
Day: 3 Scenario: Wow Units sold: 100
Day: 4 Scenario: Normal Units sold: 80
Day: 5 Scenario: Normal Units sold: 80


## normal distribution




In [3]:
# normal standard (fila 1)
# si quiero mas de un valor debo poner el numero dentro de los parentesis (fila 2) 
# si quiero una matriz debo poner la dimensiones que quiero (fila 3) 

np.random.randn()
np.random.randn(5)
np.random.randn(4,3)

array([[-0.89150826,  1.13229602, -0.7374582 ],
       [ 0.84762173,  1.14243467,  1.19589448],
       [-0.1694938 ,  0.48806089,  0.36113324],
       [-0.62295593,  0.59937303, -0.82792977]])

In [8]:
# normal 

mu = 0.01
sigma = 0.1

np.random.normal(mu,sigma)
np.random.normal(mu,sigma, size = 5)
np.random.normal(mu,sigma, size =(3,1))  

array([[-0.04324381],
       [ 0.06142491],
       [ 0.17012206]])